### ISSUE TITLE
Anyway to auto install 61-gnome-bluetooth-rfkill.rules?

### ISSUE THREAD

**Issue by simsilver** [nemofsan/calculate-gnome#1]
My laptop's bluetooth couldn't be found under gnome after setup cacluate linux and install gnome-light, while blueman works. 

Then I found and selected this profile and did cl-update, still bluetooth can't be found. Later I found profiles/templates/2_ac_install_merge/net-wireless/gnome-bluetooth/rules.d/61-gnome-bluetooth-rfkill.rules, but reinstall gnome-bluetooth with `emerge -av gnome-bluetooth --usepkg-exclude gnome-bluetooth` didn't get the rule installed. 

I copy the udev rule manually and reboot, bluetooth works now. Thanks and it saved my life ^_^

I'm new to calculate linux, is there anyway to make the udev rule get auto installed?

**Comment by nemofsan** [comment]
I fixed it in the profile and now rule 61-gnome-bluetooth-rfkill.rules is installed automatically.

**Comment by simsilver** [comment]
Test and it works, thank you!

**Comment by simsilver** [comment]
failed with gnome-bluetooth-42.8

**Comment by simsilver** [comment]
fixed in 92008d6ca8ff51b6e353211ad8ece7016559839d
